# Generated by Django 4.2.7 on 2026-02-01 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('dimensions', models.CharField(blank=True, max_length=128, verbose_name='Dimensions')),
                ('category', models.CharField(choices=[('maison', 'Maison'), ('mode', 'Mode'), ('jouet', 'Jouet'), ('bricolage', 'Bricolage'), ('culture', 'Culture'), ('sport', 'Sport'), ('meubles', 'Meubles')], max_length=32, verbose_name='Catégorie')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Photo')),
                ('image_alt', models.CharField(blank=True, max_length=255, verbose_name='Texte alternatif image')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publié')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
