# Generated by Django 4.2.27 on 2026-02-01 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('alaune', 'À la une'), ('maison', 'Maison'), ('mode', 'Mode'), ('jouet', 'Jouet'), ('bricolage', 'Bricolage'), ('culture', 'Culture'), ('sport', 'Sport'), ('meubles', 'Meubles')], max_length=32, verbose_name='Catégorie'),
        ),
    ]
